### ISSUE TITLE
Change LICENSE to MIT?

### ISSUE THREAD

**Issue by amilajack** [jdrew1303/sqltraverse#4]
Thoughts on this?

**Comment by jdrew1303** [comment]
Hey @amilajack, 

I prefer to use the MIT license for most libs. The reasoning behind using BSD in this case is the dependency of this library on `estraverse` which itself uses the BSD 2-Clause "Simplified" License. The directionality of a license is a factor. What I mean by this is that you can use an MIT licensed lib in a BSD licensed lib/app but not the other way around. In this case we couldn't release this as BSD without removing the dependency on `estraverse`. Most of the functionality of this lib comes from there and I dont think its worth reinventing the wheel to do this (unless it would stop it being used in a major project).

regards,
James
